apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-db-volume
  labels:
    type: local
spec:
  storageClassName: jira-db-volume
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/data/jiradb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - worker-1
              - worker-2
              