apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: jira
spec:
  storageClassName: jira-db-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi