apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pv-claim
  labels:
    app: jira
spec:
  storageClassName: jira-app-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi