apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: default
spec:
  config: '{
  	"cniVersion": "0.3.1",
  	"type": "macvlan",
        "name": "macvlan-conf",
        "master": "eth2",
  	"ipam": {
    	    "type": "whereabouts",
    	    "range": "172.20.0.10/24"
  	}
  }'
