- name: systemd reload
  systemd:
    daemon_reload: yes
- name: docker status
  service: name=docker state=started
- name: docker reload
  service: name=docker state=restarted  
- name: kubelet reload
  service: name=docker state=restarted  daemon_reload=yes