- name: systemd reload
  systemd:
    daemon_reload: yes
- name: containerd status
  service: name=containerd state=started
- name: containerd reload
  service: name=containerd state=restarted
- name: kubelet reload
  service: name=kubelet state=restarted  daemon_reload=yes